-- QuantMudra Job Execution Log Table
-- Tracks scheduled job runs with statistics

CREATE TABLE JOB_EXECUTION_LOG (
    LOG_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_NAME            VARCHAR2(50) NOT NULL,
    JOB_TYPE            VARCHAR2(30) NOT NULL,
    START_TIME          TIMESTAMP NOT NULL,
    END_TIME            TIMESTAMP,
    STATUS              VARCHAR2(20) NOT NULL,
    RECORDS_ADDED       NUMBER DEFAULT 0,
    RECORDS_UPDATED     NUMBER DEFAULT 0,
    RECORDS_FAILED      NUMBER DEFAULT 0,
    ERROR_MESSAGE       VARCHAR2(2000),
    DURATION_SECONDS    NUMBER,
    RUN_ENVIRONMENT     VARCHAR2(20) DEFAULT 'PRODUCTION',
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_status CHECK (STATUS IN ('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL'))
);

CREATE INDEX idx_job_exec_log_job_name ON JOB_EXECUTION_LOG(JOB_NAME);
CREATE INDEX idx_job_exec_log_start_time ON JOB_EXECUTION_LOG(START_TIME DESC);
CREATE INDEX idx_job_exec_log_status ON JOB_EXECUTION_LOG(STATUS);

-- Quick status view: last run for each job
CREATE OR REPLACE VIEW V_JOB_LAST_RUN AS
SELECT JOB_NAME, JOB_TYPE, START_TIME, END_TIME, STATUS, 
       RECORDS_ADDED, RECORDS_UPDATED, DURATION_SECONDS, ERROR_MESSAGE
FROM (
    SELECT JOB_EXECUTION_LOG.*, 
           ROW_NUMBER() OVER (PARTITION BY JOB_NAME ORDER BY START_TIME DESC) as rn
    FROM JOB_EXECUTION_LOG
)
WHERE rn = 1;

-- Daily summary view
CREATE OR REPLACE VIEW V_DAILY_JOB_SUMMARY AS
SELECT TRUNC(START_TIME) AS RUN_DATE, 
       COUNT(*) AS TOTAL_RUNS,
       SUM(RECORDS_ADDED) AS TOTAL_ADDED, 
       SUM(RECORDS_UPDATED) AS TOTAL_UPDATED,
       AVG(DURATION_SECONDS) AS AVG_DURATION_SEC
FROM JOB_EXECUTION_LOG
GROUP BY TRUNC(START_TIME);